'use server';

import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { revalidatePath } from 'next/cache';
import { calculateInvoiceTotal } from '@/lib/utils';
import { getPlatformCredentials } from '@/lib/whatsapp/config';
import { sendMessage } from '@/lib/whatsapp/templates';
import type {
  ActionResult,
  Invoice,
  CreateInvoiceInput,
  CustomerMembership,
  MembershipStatus,
  Membership,
} from '@/types';

/**
 * Get the active membership for a customer (if any).
 * Returns the membership with its discount_pct if active.
 */
export async function getCustomerActiveMembership(
  customerId: string
): Promise<{ membership: Membership; customerMembership: CustomerMembership } | null> {
  const supabase = await createClient();

  const today = new Date().toISOString().split('T')[0];

  const { data } = await supabase
    .from('customer_memberships')
    .select('*, memberships(*)')
    .eq('customer_id', customerId)
    .eq('status', 'active')
    .gte('end_date', today)
    .order('end_date', { ascending: false })
    .limit(1)
    .single();

  if (!data) return null;

  return {
    customerMembership: {
      id: data.id,
      customer_id: data.customer_id,
      membership_id: data.membership_id,
      tenant_id: data.tenant_id,
      branch_id: data.branch_id ?? '',
      start_date: data.start_date,
      end_date: data.end_date,
      status: data.status as MembershipStatus,
      created_at: data.created_at ?? '',
    },
    membership: data.memberships as unknown as Membership,
  };
}

/**
 * Create an invoice with line items.
 * Applies membership discount automatically if customer has active membership.
 * Calculates GST if provided.
 * The invoice_number is auto-generated by a database trigger.
 */
export async function createInvoice(
  input: CreateInvoiceInput
): Promise<ActionResult<Invoice>> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Not authenticated' };

  const tenantId = user.user_metadata?.tenant_id;
  const branchId = user.user_metadata?.branch_id;
  if (!tenantId || !branchId) {
    return { success: false, error: 'No tenant or branch context found.' };
  }

  if (!input.customer_id) {
    return { success: false, error: 'Customer is required.' };
  }
  if (!input.items || input.items.length === 0) {
    return { success: false, error: 'At least one service item is required.' };
  }
  if (!input.payment_method) {
    return { success: false, error: 'Payment method is required.' };
  }

  // Calculate totals
  const discountPct = input.discount_pct ?? 0;
  const gstRate = input.gst_rate ?? 0;

  const totals = calculateInvoiceTotal({
    lineItems: input.items.map((item) => ({
      price: item.unit_price,
      quantity: item.quantity,
    })),
    membershipDiscountPct: discountPct,
    gstRate: gstRate,
  });

  // Insert invoice (invoice_number is auto-generated by DB trigger)
  const { data: invoice, error: invoiceError } = await supabase
    .from('invoices')
    .insert({
      tenant_id: tenantId,
      branch_id: branchId,
      customer_id: input.customer_id,
      appointment_id: input.appointment_id ?? null,
      invoice_number: '', // trigger will generate
      subtotal: totals.subtotal,
      discount_amount: totals.discountAmount,
      discount_pct: discountPct,
      gst_amount: totals.gstAmount,
      gst_rate: gstRate,
      total: totals.total,
      payment_method: input.payment_method,
      payment_status: 'paid',
      delivery_status: 'pending',
    })
    .select()
    .single();

  if (invoiceError) {
    console.error('Invoice creation error:', invoiceError);
    return { success: false, error: 'Failed to create invoice. Please try again.' };
  }

  // Insert invoice items
  const invoiceItems = input.items.map((item) => ({
    invoice_id: invoice.id,
    service_id: item.service_id,
    service_name: item.service_name,
    unit_price: item.unit_price,
    quantity: item.quantity,
    line_total: item.unit_price * item.quantity,
  }));

  const { error: itemsError } = await supabase
    .from('invoice_items')
    .insert(invoiceItems);

  if (itemsError) {
    console.error('Invoice items creation error:', itemsError);
    // Invoice was created but items failed — still return the invoice
    return { success: true, data: invoice as Invoice };
  }

  // Send bill receipt to customer via WhatsApp + feedback request
  await sendBillReceiptWhatsApp(
    tenantId,
    input.customer_id,
    input.items,
    invoice.invoice_number,
    totals.subtotal,
    discountPct,
    totals.discountAmount,
    totals.total,
    input.payment_method
  );

  revalidatePath('/dashboard/billing');
  return { success: true, data: invoice as Invoice };
}

/**
 * Send an invoice via WhatsApp (placeholder — calls Edge Function).
 */
export async function sendInvoiceWhatsApp(invoiceId: string): Promise<ActionResult<void>> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Not authenticated' };

  // Call the send-invoice Edge Function
  const { error } = await supabase.functions.invoke('send-invoice', {
    body: { invoice_id: invoiceId },
  });

  if (error) {
    return { success: false, error: 'Failed to send invoice via WhatsApp. Please try again.' };
  }

  revalidatePath('/dashboard/billing');
  return { success: true, data: undefined };
}

/**
 * Update an invoice's payment method and payment status.
 */
export async function updateInvoicePayment(
  invoiceId: string,
  updates: { payment_method: 'cash' | 'upi' | 'card'; payment_status: 'paid' | 'partial' | 'pending' }
): Promise<ActionResult<void>> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Not authenticated' };

  const { error } = await supabase
    .from('invoices')
    .update({
      payment_method: updates.payment_method,
      payment_status: updates.payment_status,
    })
    .eq('id', invoiceId);

  if (error) {
    return { success: false, error: 'Failed to update invoice. Please try again.' };
  }

  revalidatePath('/dashboard/billing');
  return { success: true, data: undefined };
}

/**
 * Get the tenant's GST and discount settings.
 */
export async function getTenantGstSettings(): Promise<{ gst_enabled: boolean; gst_rate: number; gst_number: string | null; discount_enabled: boolean; discount_value: number }> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { gst_enabled: false, gst_rate: 0, gst_number: null, discount_enabled: false, discount_value: 0 };

  const tenantId = user.user_metadata?.tenant_id;
  if (!tenantId) return { gst_enabled: false, gst_rate: 0, gst_number: null, discount_enabled: false, discount_value: 0 };

  const { data: tenant } = await supabase
    .from('tenants')
    .select('settings')
    .eq('id', tenantId)
    .single();

  if (!tenant) return { gst_enabled: false, gst_rate: 0, gst_number: null, discount_enabled: false, discount_value: 0 };

  const settings = (tenant.settings as Record<string, unknown>) ?? {};
  return {
    gst_enabled: (settings.gst_enabled as boolean) ?? false,
    gst_rate: (settings.gst_rate as number) ?? 18,
    gst_number: (settings.gst_number as string) ?? null,
    discount_enabled: (settings.discount_enabled as boolean) ?? false,
    discount_value: (settings.discount_value as number) ?? 0,
  };
}

// =============================================================================
// WhatsApp Bill Receipt Notification
// =============================================================================

/**
 * Send bill receipt to customer via WhatsApp after creating an invoice.
 */
async function sendBillReceiptWhatsApp(
  tenantId: string,
  customerId: string,
  items: { service_name: string; unit_price: number; quantity: number }[],
  invoiceNumber: string,
  subtotal: number,
  discountPct: number,
  discountAmount: number,
  total: number,
  paymentMethod: string
) {
  try {
    console.log('[BillReceipt] Starting for customer:', customerId, 'tenant:', tenantId);
    const admin = createAdminClient();
    const credentials = getPlatformCredentials();
    if (!credentials) {
      console.log('[BillReceipt] No credentials found');
      return;
    }

    // Get customer phone and name
    const { data: customer, error: custErr } = await admin
      .from('customers')
      .select('name, phone')
      .eq('id', customerId)
      .single();

    console.log('[BillReceipt] Customer:', customer?.name, customer?.phone, 'Error:', custErr?.message);

    if (!customer?.phone) return;

    // Get salon name and tenant code for booking link
    const { data: tenant } = await (admin.from('tenants' as any).select('name, tenant_code').eq('id', tenantId).single() as any);
    const salonName = ((tenant?.name as string) || 'the salon').trim();

    // Build service list
    const serviceLines = items.map((s) => `  • ${s.service_name} — ₹${s.unit_price.toLocaleString('en-IN')}${s.quantity > 1 ? ` x${s.quantity}` : ''}`).join('\n');

    // Build bill message
    let billText = `🧾 *Bill Receipt*\n\n`;
    billText += `Hi ${customer.name}, thank you for visiting *${salonName}*! Here's your bill:\n\n`;
    billText += `📋 *Invoice:* ${invoiceNumber}\n\n`;
    billText += `*Services:*\n${serviceLines}\n\n`;
    billText += `━━━━━━━━━━━━━━━\n`;
    if (discountPct > 0) {
      billText += `Subtotal: ₹${subtotal.toLocaleString('en-IN')}\n`;
      billText += `Discount (${discountPct}%): -₹${discountAmount.toLocaleString('en-IN')}\n`;
    }
    billText += `*Total: ₹${total.toLocaleString('en-IN')}*\n`;
    billText += `Payment: ${paymentMethod.toUpperCase()}\n`;
    billText += `━━━━━━━━━━━━━━━\n\n`;
    billText += `Thank you for choosing us! 😊`;

    const phone = customer.phone.replace(/\D/g, '');
    console.log('[BillReceipt] Sending to phone:', phone);

    // Use approved template (works outside 24-hour window)
    const serviceList = items.map((s) => s.service_name).join(', ');
    const sendResult = await sendMessage(credentials, phone, {
      type: 'template',
      template: {
        name: 'bill_receipt_v1',
        language: { code: 'en' },
        components: [
          {
            type: 'body',
            parameters: [
              { type: 'text', text: customer.name },
              { type: 'text', text: salonName },
              { type: 'text', text: invoiceNumber },
              { type: 'text', text: serviceList },
              { type: 'text', text: String(total) },
              { type: 'text', text: paymentMethod.toUpperCase() },
            ],
          },
        ],
      },
    });
    console.log('[BillReceipt] Send result:', JSON.stringify(sendResult));

    // Log bill receipt to whatsapp_sessions
    await (admin.from('whatsapp_sessions').insert({
      tenant_id: tenantId,
      message_id: `bill_${Date.now()}`,
      phone,
      direction: 'outbound',
      template_name: 'bill_receipt',
      status: 'sent',
      metadata: { customer_name: customer.name },
    } as any) as any);

    // Send feedback request using approved template (works outside 24h window)
    await sendMessage(credentials, phone, {
      type: 'template',
      template: {
        name: 'feedback_request_v1',
        language: { code: 'en' },
        components: [
          {
            type: 'body',
            parameters: [
              { type: 'text', text: customer.name },
              { type: 'text', text: salonName },
            ],
          },
        ],
      },
    });

    // CRITICAL: Update customer session to this tenant AFTER sending feedback request.
    // This ensures when customer taps "Rate Now", the webhook routes to the correct tenant.
    const expiresAt = new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(); // 48 hours
    await (admin
      .from('whatsapp_customer_sessions' as any)
      .delete()
      .eq('customer_phone', phone) as any);
    await (admin
      .from('whatsapp_customer_sessions' as any)
      .insert({
        tenant_id: tenantId,
        customer_phone: phone,
        mode: 'shared',
        source: 'bill_feedback',
        current_state: 'awaiting_feedback',
        booking_slug: tenant?.tenant_code || '',
        last_message_at: new Date().toISOString(),
        expires_at: expiresAt,
      }) as any);

    // Log feedback request to whatsapp_sessions
    await (admin.from('whatsapp_sessions').insert({
      tenant_id: tenantId,
      message_id: `feedback_req_${Date.now()}`,
      phone,
      direction: 'outbound',
      template_name: 'feedback_request',
      status: 'sent',
      metadata: { customer_name: customer.name },
    } as any) as any);
  } catch (err) {
    console.error('[Billing] Failed to send bill receipt via WhatsApp:', err);
  }
}

// =============================================================================
// Invoice Document Data (for premium print / download)
// =============================================================================

export interface InvoiceDocumentItem {
  service_name: string;
  unit_price: number;
  quantity: number;
  line_total: number;
}

export interface InvoiceDocument {
  invoice_number: string;
  created_at: string;
  payment_method: string;
  payment_status: string;
  subtotal: number;
  discount_pct: number;
  discount_amount: number;
  gst_rate: number;
  gst_amount: number;
  total: number;
  items: InvoiceDocumentItem[];
  customer: { name: string; phone: string | null; email: string | null };
  salon: {
    name: string;
    address: string | null;
    phone: string | null;
    email: string | null;
    gst_number: string | null;
  };
}

/**
 * Fetch the full invoice document (invoice + items + customer + salon)
 * for rendering a premium printable/downloadable receipt.
 * RLS scopes the invoice to the current tenant.
 */
export async function getInvoiceDocument(
  invoiceId: string
): Promise<ActionResult<InvoiceDocument>> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Not authenticated' };

  const tenantId = user.user_metadata?.tenant_id as string | undefined;
  if (!tenantId) return { success: false, error: 'No tenant context found.' };

  // Fetch invoice (RLS-scoped)
  const { data: invoice, error: invErr } = await supabase
    .from('invoices')
    .select('id, invoice_number, created_at, payment_method, payment_status, subtotal, discount_pct, discount_amount, gst_rate, gst_amount, total, customer_id, branch_id')
    .eq('id', invoiceId)
    .single();

  if (invErr || !invoice) {
    return { success: false, error: 'Invoice not found.' };
  }

  // Fetch line items, customer, tenant, and branch in parallel
  const [itemsRes, customerRes, tenantRes, branchRes] = await Promise.all([
    supabase
      .from('invoice_items')
      .select('service_name, unit_price, quantity, line_total')
      .eq('invoice_id', invoiceId),
    invoice.customer_id
      ? supabase.from('customers').select('name, phone, email').eq('id', invoice.customer_id).single()
      : Promise.resolve({ data: null }),
    supabase.from('tenants').select('name, phone, settings').eq('id', tenantId).single(),
    invoice.branch_id
      ? supabase.from('branches').select('name, address, phone').eq('id', invoice.branch_id).single()
      : Promise.resolve({ data: null }),
  ]);

  const settings = ((tenantRes.data?.settings as Record<string, unknown>) ?? {});
  const customer = (customerRes.data as { name: string; phone: string | null; email: string | null } | null);
  const branch = (branchRes.data as { name: string; address: string | null; phone: string | null } | null);

  const doc: InvoiceDocument = {
    invoice_number: invoice.invoice_number,
    created_at: invoice.created_at ?? new Date().toISOString(),
    payment_method: invoice.payment_method ?? 'cash',
    payment_status: invoice.payment_status ?? 'paid',
    subtotal: invoice.subtotal ?? 0,
    discount_pct: invoice.discount_pct ?? 0,
    discount_amount: invoice.discount_amount ?? 0,
    gst_rate: invoice.gst_rate ?? 0,
    gst_amount: invoice.gst_amount ?? 0,
    total: invoice.total ?? 0,
    items: (itemsRes.data ?? []).map((it: any) => ({
      service_name: it.service_name,
      unit_price: it.unit_price,
      quantity: it.quantity,
      line_total: it.line_total ?? it.unit_price * it.quantity,
    })),
    customer: {
      name: customer?.name ?? '—',
      phone: customer?.phone ?? null,
      email: customer?.email ?? null,
    },
    salon: {
      name: (tenantRes.data?.name as string) ?? 'Salon',
      address: branch?.address ?? null,
      phone: branch?.phone ?? (tenantRes.data?.phone as string) ?? null,
      email: (settings.email as string) ?? null,
      gst_number: (settings.gst_number as string) ?? null,
    },
  };

  return { success: true, data: doc };
}
