'use server';

import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { revalidatePath } from 'next/cache';
import { calculateInvoiceTotal } from '@/lib/utils';
import { sendBillReceiptWithPdf } from '@/lib/invoice/send-bill-receipt';
import type {
  ActionResult,
  Invoice,
  CreateInvoiceInput,
  CustomerMembership,
  MembershipStatus,
  Membership,
} from '@/types';

/**
 * Get the active membership for a customer (if any).
 * Returns the membership with its discount_pct if active.
 */
export async function getCustomerActiveMembership(
  customerId: string
): Promise<{ membership: Membership; customerMembership: CustomerMembership } | null> {
  const supabase = await createClient();

  const today = new Date().toISOString().split('T')[0];

  const { data } = await supabase
    .from('customer_memberships')
    .select('*, memberships(*)')
    .eq('customer_id', customerId)
    .eq('status', 'active')
    .gte('end_date', today)
    .order('end_date', { ascending: false })
    .limit(1)
    .single();

  if (!data) return null;

  return {
    customerMembership: {
      id: data.id,
      customer_id: data.customer_id,
      membership_id: data.membership_id,
      tenant_id: data.tenant_id,
      branch_id: data.branch_id ?? '',
      start_date: data.start_date,
      end_date: data.end_date,
      status: data.status as MembershipStatus,
      created_at: data.created_at ?? '',
    },
    membership: data.memberships as unknown as Membership,
  };
}

/**
 * Create an invoice with line items.
 * Applies membership discount automatically if customer has active membership.
 * Calculates GST if provided.
 * The invoice_number is auto-generated by a database trigger.
 */
export async function createInvoice(
  input: CreateInvoiceInput
): Promise<ActionResult<Invoice>> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Not authenticated' };

  const tenantId = user.user_metadata?.tenant_id;
  const branchId = user.user_metadata?.branch_id;
  if (!tenantId || !branchId) {
    return { success: false, error: 'No tenant or branch context found.' };
  }

  if (!input.customer_id) {
    return { success: false, error: 'Customer is required.' };
  }
  if (!input.items || input.items.length === 0) {
    return { success: false, error: 'At least one service item is required.' };
  }
  if (!input.payment_method) {
    return { success: false, error: 'Payment method is required.' };
  }

  // Calculate totals
  const discountPct = input.discount_pct ?? 0;
  const gstRate = input.gst_rate ?? 0;

  const totals = calculateInvoiceTotal({
    lineItems: input.items.map((item) => ({
      price: item.unit_price,
      quantity: item.quantity,
    })),
    membershipDiscountPct: discountPct,
    gstRate: gstRate,
  });

  // Insert invoice (invoice_number is auto-generated by DB trigger)
  const { data: invoice, error: invoiceError } = await supabase
    .from('invoices')
    .insert({
      tenant_id: tenantId,
      branch_id: branchId,
      customer_id: input.customer_id,
      appointment_id: input.appointment_id ?? null,
      invoice_number: '', // trigger will generate
      subtotal: totals.subtotal,
      discount_amount: totals.discountAmount,
      discount_pct: discountPct,
      gst_amount: totals.gstAmount,
      gst_rate: gstRate,
      total: totals.total,
      payment_method: input.payment_method,
      payment_status: 'paid',
      delivery_status: 'pending',
    })
    .select()
    .single();

  if (invoiceError) {
    console.error('Invoice creation error:', invoiceError);
    return { success: false, error: 'Failed to create invoice. Please try again.' };
  }

  // Insert invoice items
  const invoiceItems = input.items.map((item) => ({
    invoice_id: invoice.id,
    service_id: item.service_id,
    service_name: item.service_name,
    unit_price: item.unit_price,
    quantity: item.quantity,
    line_total: item.unit_price * item.quantity,
  }));

  const { error: itemsError } = await supabase
    .from('invoice_items')
    .insert(invoiceItems);

  if (itemsError) {
    console.error('Invoice items creation error:', itemsError);
    // Invoice was created but items failed — still return the invoice
    return { success: true, data: invoice as Invoice };
  }

  // Send bill receipt to customer via WhatsApp + feedback request
  await sendBillReceiptWhatsApp(
    tenantId,
    input.customer_id,
    input.items,
    invoice.invoice_number,
    totals.subtotal,
    discountPct,
    totals.discountAmount,
    totals.total,
    input.payment_method
  );

  revalidatePath('/dashboard/billing');
  return { success: true, data: invoice as Invoice };
}

/**
 * Send an invoice via WhatsApp (placeholder — calls Edge Function).
 */
export async function sendInvoiceWhatsApp(invoiceId: string): Promise<ActionResult<void>> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Not authenticated' };

  // Call the send-invoice Edge Function
  const { error } = await supabase.functions.invoke('send-invoice', {
    body: { invoice_id: invoiceId },
  });

  if (error) {
    return { success: false, error: 'Failed to send invoice via WhatsApp. Please try again.' };
  }

  revalidatePath('/dashboard/billing');
  return { success: true, data: undefined };
}

/**
 * Update an invoice's payment method and payment status.
 */
export async function updateInvoicePayment(
  invoiceId: string,
  updates: { payment_method: 'cash' | 'upi' | 'card'; payment_status: 'paid' | 'partial' | 'pending' }
): Promise<ActionResult<void>> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Not authenticated' };

  const { error } = await supabase
    .from('invoices')
    .update({
      payment_method: updates.payment_method,
      payment_status: updates.payment_status,
    })
    .eq('id', invoiceId);

  if (error) {
    return { success: false, error: 'Failed to update invoice. Please try again.' };
  }

  revalidatePath('/dashboard/billing');
  return { success: true, data: undefined };
}

/**
 * Get the tenant's GST and discount settings.
 */
export async function getTenantGstSettings(): Promise<{ gst_enabled: boolean; gst_rate: number; gst_number: string | null; discount_enabled: boolean; discount_value: number }> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { gst_enabled: false, gst_rate: 0, gst_number: null, discount_enabled: false, discount_value: 0 };

  const tenantId = user.user_metadata?.tenant_id;
  if (!tenantId) return { gst_enabled: false, gst_rate: 0, gst_number: null, discount_enabled: false, discount_value: 0 };

  const { data: tenant } = await supabase
    .from('tenants')
    .select('settings')
    .eq('id', tenantId)
    .single();

  if (!tenant) return { gst_enabled: false, gst_rate: 0, gst_number: null, discount_enabled: false, discount_value: 0 };

  const settings = (tenant.settings as Record<string, unknown>) ?? {};
  const gstEnabled = (settings.gst_enabled as boolean) ?? false;
  // India: hair salons & beauty spas attract 5% GST on services. Default to 5%
  // when GST is enabled but no explicit rate has been stored.
  const storedRate = (settings.gst_rate as number) ?? 0;
  return {
    gst_enabled: gstEnabled,
    gst_rate: gstEnabled ? (storedRate > 0 ? storedRate : 5) : 0,
    gst_number: (settings.gst_number as string) ?? null,
    discount_enabled: (settings.discount_enabled as boolean) ?? false,
    discount_value: (settings.discount_value as number) ?? 0,
  };
}

// =============================================================================
// WhatsApp Bill Receipt Notification
// =============================================================================

/**
 * Send bill receipt to customer via WhatsApp after creating an invoice.
 * Delegates to the shared sender so this path and the appointment-completion
 * path stay identical (PDF attached via bill_receipt_v2 + feedback request).
 */
async function sendBillReceiptWhatsApp(
  tenantId: string,
  customerId: string,
  items: { service_name: string; unit_price: number; quantity: number }[],
  invoiceNumber: string,
  subtotal: number,
  discountPct: number,
  discountAmount: number,
  total: number,
  paymentMethod: string
) {
  await sendBillReceiptWithPdf({
    tenantId,
    customerId,
    items,
    invoiceNumber,
    total,
    paymentMethod,
  });
}

// =============================================================================
// Invoice Document Data (for premium print / download)
// =============================================================================

export interface InvoiceDocumentItem {
  service_name: string;
  unit_price: number;
  quantity: number;
  line_total: number;
}

export interface InvoiceDocument {
  invoice_number: string;
  created_at: string;
  payment_method: string;
  payment_status: string;
  subtotal: number;
  discount_pct: number;
  discount_amount: number;
  gst_rate: number;
  gst_amount: number;
  total: number;
  items: InvoiceDocumentItem[];
  customer: { name: string; phone: string | null; email: string | null };
  salon: {
    name: string;
    legal_name: string | null;
    trade_name: string | null;
    address: string | null;
    phone: string | null;
    email: string | null;
    gst_number: string | null;
  };
}

/**
 * Fetch the full invoice document (invoice + items + customer + salon)
 * for rendering a premium printable/downloadable receipt.
 * RLS scopes the invoice to the current tenant.
 */
export async function getInvoiceDocument(
  invoiceId: string
): Promise<ActionResult<InvoiceDocument>> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { success: false, error: 'Not authenticated' };

  const tenantId = user.user_metadata?.tenant_id as string | undefined;
  if (!tenantId) return { success: false, error: 'No tenant context found.' };

  // Fetch invoice (RLS-scoped)
  const { data: invoice, error: invErr } = await supabase
    .from('invoices')
    .select('id, invoice_number, created_at, payment_method, payment_status, subtotal, discount_pct, discount_amount, gst_rate, gst_amount, total, customer_id, branch_id')
    .eq('id', invoiceId)
    .single();

  if (invErr || !invoice) {
    return { success: false, error: 'Invoice not found.' };
  }

  // Fetch line items, customer, tenant, and branch in parallel
  const [itemsRes, customerRes, tenantRes, branchRes] = await Promise.all([
    supabase
      .from('invoice_items')
      .select('service_name, unit_price, quantity, line_total')
      .eq('invoice_id', invoiceId),
    invoice.customer_id
      ? supabase.from('customers').select('name, phone, email').eq('id', invoice.customer_id).single()
      : Promise.resolve({ data: null }),
    supabase.from('tenants').select('name, phone, settings').eq('id', tenantId).single(),
    invoice.branch_id
      ? supabase.from('branches').select('name, address, phone').eq('id', invoice.branch_id).single()
      : Promise.resolve({ data: null }),
  ]);

  const settings = ((tenantRes.data?.settings as Record<string, unknown>) ?? {});
  const customer = (customerRes.data as { name: string; phone: string | null; email: string | null } | null);
  const branch = (branchRes.data as { name: string; address: string | null; phone: string | null } | null);

  const doc: InvoiceDocument = {
    invoice_number: invoice.invoice_number,
    created_at: invoice.created_at ?? new Date().toISOString(),
    payment_method: invoice.payment_method ?? 'cash',
    payment_status: invoice.payment_status ?? 'paid',
    subtotal: invoice.subtotal ?? 0,
    discount_pct: invoice.discount_pct ?? 0,
    discount_amount: invoice.discount_amount ?? 0,
    gst_rate: invoice.gst_rate ?? 0,
    gst_amount: invoice.gst_amount ?? 0,
    total: invoice.total ?? 0,
    items: (itemsRes.data ?? []).map((it: any) => ({
      service_name: it.service_name,
      unit_price: it.unit_price,
      quantity: it.quantity,
      line_total: it.line_total ?? it.unit_price * it.quantity,
    })),
    customer: {
      name: customer?.name ?? '—',
      phone: customer?.phone ?? null,
      email: customer?.email ?? null,
    },
    salon: {
      name: (tenantRes.data?.name as string) ?? 'Salon',
      legal_name: (settings.legal_name as string) ?? null,
      trade_name: (settings.trade_name as string) ?? null,
      address: branch?.address ?? null,
      phone: branch?.phone ?? (tenantRes.data?.phone as string) ?? null,
      email: (settings.email as string) ?? null,
      gst_number: (settings.gst_number as string) ?? null,
    },
  };

  return { success: true, data: doc };
}
