'use client';

import { useEffect, useState } from 'react';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell,
  PieChart, Pie, Legend,
} from 'recharts';
import { TrendingUp, Users, IndianRupee, Scissors, Trophy, Loader2 } from 'lucide-react';
import { formatINR } from '@/lib/utils';
import { ExportButton } from '@/components/export-button';
import { getStaffPerformance, type StaffPerformanceResult } from './actions';

// =============================================================================
// Staff Performance — premium metrics panel with charts.
// =============================================================================

const RANGES = [
  { label: '7 days', value: 7 },
  { label: '30 days', value: 30 },
  { label: '90 days', value: 90 },
];

// Brand-aligned palette for chart slices/bars.
const COLORS = ['#db2777', '#a21caf', '#7c3aed', '#0ea5e9', '#10b981', '#f59e0b', '#ef4444', '#6366f1'];

export function StaffPerformance() {
  const [days, setDays] = useState(30);
  const [data, setData] = useState<StaffPerformanceResult | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;
    setLoading(true);
    getStaffPerformance(days).then((res) => {
      if (active) { setData(res); setLoading(false); }
    });
    return () => { active = false; };
  }, [days]);

  const staff = data?.staff ?? [];
  const totals = data?.totals ?? { revenue: 0, customers: 0, services: 0 };
  const unattributed = data?.unattributed ?? { revenue: 0, services: 0 };
  const topPerformer = staff[0] ?? null;

  const revenueChart = staff.map((s) => ({ name: s.name, revenue: s.revenue }));
  const shareChart = staff
    .filter((s) => s.revenue > 0)
    .map((s) => ({ name: s.name, value: s.revenue }));

  return (
    <div className="rounded-2xl border border-border bg-card overflow-hidden">
      {/* Header */}
      <div className="flex flex-col gap-3 border-b border-border bg-gradient-to-br from-violet-500/5 to-transparent px-4 py-4 sm:px-6 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2.5">
          <div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-violet-100 dark:bg-violet-900/30">
            <TrendingUp className="size-4 text-violet-600 dark:text-violet-400" />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-foreground">Staff Performance</h2>
            <p className="text-xs text-muted-foreground">Customers served and revenue generated by each team member</p>
          </div>
        </div>
        {/* Range tabs */}
        <div className="flex items-center gap-2 w-full sm:w-auto">
          <div className="flex flex-1 items-center rounded-xl border border-border bg-muted/50 p-1 sm:flex-none">
            {RANGES.map((r) => (
              <button
                key={r.value}
                onClick={() => setDays(r.value)}
                className={`flex-1 sm:flex-none rounded-lg px-3 py-1.5 text-xs font-medium transition-all ${
                  days === r.value ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                {r.label}
              </button>
            ))}
          </div>
          <ExportButton
            filename={`staff-performance-${days}d`}
            label="Export"
            rows={staff}
            columns={[
              { header: 'Staff', value: (s) => s.name },
              { header: 'Role', value: (s) => s.role },
              { header: 'Customers Served', value: (s) => s.customersServed },
              { header: 'Services Billed', value: (s) => s.servicesCount },
              { header: 'Avg Ticket (INR)', value: (s) => s.avgTicket },
              { header: 'Revenue (INR)', value: (s) => s.revenue },
            ]}
          />
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-16">
          <Loader2 className="size-6 animate-spin text-muted-foreground" />
        </div>
      ) : staff.length === 0 && unattributed.services === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <div className="flex size-12 items-center justify-center rounded-full bg-muted mb-3">
            <Users className="size-6 text-muted-foreground" />
          </div>
          <p className="text-sm font-medium text-foreground">No performance data yet</p>
          <p className="text-xs text-muted-foreground mt-1 max-w-xs">
            Complete appointments and generate bills with a staff member selected to see their performance here.
          </p>
        </div>
      ) : (
        <div className="p-4 sm:p-6 space-y-6">
          {/* Summary stat cards */}
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <StatCard icon={<IndianRupee className="size-4" />} tint="emerald" label="Total Revenue" value={formatINR(totals.revenue)} />
            <StatCard icon={<Users className="size-4" />} tint="blue" label="Customers Served" value={String(totals.customers)} />
            <StatCard icon={<Scissors className="size-4" />} tint="violet" label="Services Billed" value={String(totals.services)} />
            <StatCard
              icon={<Trophy className="size-4" />}
              tint="amber"
              label="Top Performer"
              value={topPerformer?.name ?? '—'}
              sub={topPerformer ? formatINR(topPerformer.revenue) : undefined}
            />
          </div>

          {/* Charts */}
          <div className="grid gap-6 lg:grid-cols-5">
            {/* Revenue by staff — bar */}
            <div className="lg:col-span-3 rounded-xl border border-border p-4">
              <p className="text-xs font-semibold text-foreground mb-3">Revenue by staff</p>
              <ResponsiveContainer width="100%" height={260}>
                <BarChart data={revenueChart} margin={{ top: 4, right: 8, left: 8, bottom: 4 }}>
                  <XAxis dataKey="name" tick={{ fontSize: 11 }} stroke="currentColor" className="text-muted-foreground" interval={0} angle={-12} textAnchor="end" height={48} />
                  <YAxis tick={{ fontSize: 11 }} stroke="currentColor" className="text-muted-foreground" tickFormatter={(v) => `₹${v >= 1000 ? `${Math.round(v / 1000)}k` : v}`} />
                  <Tooltip
                    cursor={{ fill: 'rgba(168,85,247,0.06)' }}
                    formatter={(v) => [formatINR(Number(v)), 'Revenue']}
                    contentStyle={{ borderRadius: 12, border: '1px solid var(--border)', fontSize: 12 }}
                  />
                  <Bar dataKey="revenue" radius={[6, 6, 0, 0]}>
                    {revenueChart.map((_, i) => (
                      <Cell key={i} fill={COLORS[i % COLORS.length]} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Revenue share — donut */}
            <div className="lg:col-span-2 rounded-xl border border-border p-4">
              <p className="text-xs font-semibold text-foreground mb-3">Revenue share</p>
              <ResponsiveContainer width="100%" height={260}>
                <PieChart>
                  <Pie data={shareChart} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={48} outerRadius={80} paddingAngle={2}>
                    {shareChart.map((_, i) => (
                      <Cell key={i} fill={COLORS[i % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(v) => formatINR(Number(v))} contentStyle={{ borderRadius: 12, border: '1px solid var(--border)', fontSize: 12 }} />
                  <Legend wrapperStyle={{ fontSize: 11 }} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Leaderboard table */}
          <div className="rounded-xl border border-border overflow-hidden">
            <div className="grid grid-cols-12 gap-2 bg-muted/40 px-4 py-2.5 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
              <div className="col-span-5 sm:col-span-4">Staff</div>
              <div className="col-span-3 sm:col-span-2 text-center">Customers</div>
              <div className="hidden sm:block sm:col-span-2 text-center">Services</div>
              <div className="hidden sm:block sm:col-span-2 text-right">Avg ticket</div>
              <div className="col-span-4 sm:col-span-2 text-right">Revenue</div>
            </div>
            {staff.map((s, i) => (
              <div key={s.employeeId} className="grid grid-cols-12 gap-2 items-center border-t border-border px-4 py-3 text-sm">
                <div className="col-span-5 sm:col-span-4 flex items-center gap-2.5 min-w-0">
                  <span className="flex size-7 shrink-0 items-center justify-center rounded-full text-xs font-bold text-white" style={{ background: COLORS[i % COLORS.length] }}>
                    {s.name.charAt(0).toUpperCase()}
                  </span>
                  <div className="min-w-0">
                    <p className="truncate font-medium text-foreground">{s.name}</p>
                    <p className="text-[11px] capitalize text-muted-foreground">{s.role}</p>
                  </div>
                </div>
                <div className="col-span-3 sm:col-span-2 text-center text-foreground">{s.customersServed}</div>
                <div className="hidden sm:block sm:col-span-2 text-center text-foreground">{s.servicesCount}</div>
                <div className="hidden sm:block sm:col-span-2 text-right text-muted-foreground">{formatINR(s.avgTicket)}</div>
                <div className="col-span-4 sm:col-span-2 text-right font-semibold text-foreground">{formatINR(s.revenue)}</div>
              </div>
            ))}

            {/* Unattributed — bills not linked to a staff member, so totals reconcile */}
            {unattributed.services > 0 && (
              <div className="grid grid-cols-12 gap-2 items-center border-t border-border bg-muted/30 px-4 py-3 text-sm">
                <div className="col-span-5 sm:col-span-4 flex items-center gap-2.5 min-w-0">
                  <span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-bold text-muted-foreground">
                    ?
                  </span>
                  <div className="min-w-0">
                    <p className="truncate font-medium text-muted-foreground">Unattributed</p>
                    <p className="text-[11px] text-muted-foreground">No staff recorded</p>
                  </div>
                </div>
                <div className="col-span-3 sm:col-span-2 text-center text-muted-foreground">—</div>
                <div className="hidden sm:block sm:col-span-2 text-center text-muted-foreground">{unattributed.services}</div>
                <div className="hidden sm:block sm:col-span-2 text-right text-muted-foreground">—</div>
                <div className="col-span-4 sm:col-span-2 text-right font-semibold text-muted-foreground">{formatINR(unattributed.revenue)}</div>
              </div>
            )}

            {/* Total row — reconciles to full billed revenue in range */}
            <div className="grid grid-cols-12 gap-2 items-center border-t-2 border-border bg-muted/50 px-4 py-3 text-sm">
              <div className="col-span-5 sm:col-span-4 font-semibold text-foreground">Total</div>
              <div className="col-span-3 sm:col-span-2 text-center font-semibold text-foreground">{totals.customers}</div>
              <div className="hidden sm:block sm:col-span-2 text-center font-semibold text-foreground">{totals.services}</div>
              <div className="hidden sm:block sm:col-span-2 text-right text-muted-foreground">—</div>
              <div className="col-span-4 sm:col-span-2 text-right font-bold text-foreground">{formatINR(totals.revenue)}</div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function StatCard({ icon, label, value, sub, tint }: {
  icon: React.ReactNode;
  label: string;
  value: string;
  sub?: string;
  tint: 'emerald' | 'blue' | 'violet' | 'amber';
}) {
  const tints: Record<string, string> = {
    emerald: 'bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400',
    blue: 'bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400',
    violet: 'bg-violet-100 text-violet-600 dark:bg-violet-900/30 dark:text-violet-400',
    amber: 'bg-amber-100 text-amber-600 dark:bg-amber-900/30 dark:text-amber-400',
  };
  return (
    <div className="rounded-xl border border-border p-4">
      <div className={`flex size-8 items-center justify-center rounded-lg ${tints[tint]}`}>{icon}</div>
      <p className="mt-2.5 text-lg font-bold text-foreground truncate">{value}</p>
      <p className="text-xs text-muted-foreground">{label}</p>
      {sub && <p className="text-[11px] font-medium text-amber-600 dark:text-amber-400 mt-0.5">{sub}</p>}
    </div>
  );
}
